title: "Anirudha Dhopate"
description: "Director | Senior Engineering Manager | Global Engineering & GenAI Leader"

#theme: jekyll-theme-primer

markdown: kramdown
kramdown:
  input: GFM

show_downloads: false

#plugins:
#  - jekyll-seo-tag
